# Interface CR for N4 (SMF ↔ UPF control plane)
# This is the CRD that nad-fn actually reads (NOT NetworkIntent)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /n4
  name: n4
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.nad-test
    specializer.nephio.org/namespace: default
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|default|n4'
spec:
  networkInstance:
    name: vpc-internal
  cniType: macvlan
  attachmentType: vlan
