# IPClaim for N4 interface - PRE-FILLED with status
# In the full pipeline, interface-fn creates this and resource-backend fills status
# For Phase 1 testing, we pre-fill it to prove nad-fn works
#
# CRITICAL: owner must be the Interface (not NFDeployment)
# This is how condkptsdk links IPClaims to their parent Interface
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPClaim
metadata: # kpt-merge: /n4-ipv4
  name: n4-ipv4
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n4
    internal.kpt.dev/upstream-identifier: 'ipam.resource.nephio.org|IPClaim|default|n4-ipv4'
spec:
  kind: network
  networkInstance:
    name: vpc-internal
status:
  prefix: "192.168.30.10/24"
  gateway: "192.168.30.1"
