apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: sdcore5g-cp/metricfunc
  name: metricfunc
  namespace: sdcore5g-cp
  labels:
    release: sdcore5g
    app: metricfunc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|sdcore5g-cp|metricfunc'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: sdcore5g-cp/metricfunc
  name: metricfunc
  namespace: sdcore5g-cp
  labels:
    release: sdcore5g
    app: metricfunc
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|sdcore5g-cp|metricfunc'
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  - apps
  verbs:
  - get
  - list
  - patch
  resources:
  - statefulsets
  - daemonsets
  - jobs
  - pods
  - services
  - endpoints
  - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: sdcore5g-cp/metricfunc
  name: metricfunc
  namespace: sdcore5g-cp
  labels:
    release: sdcore5g
    app: metricfunc
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|sdcore5g-cp|metricfunc'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metricfunc
subjects:
- kind: ServiceAccount
  name: metricfunc
  namespace: sdcore5g-cp
