apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPClaim
metadata:
  name: smf-sdcore-n4-ipv4
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/for: workload.nephio.org/v1alpha1.NFDeployment.smf-sdcore
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n4
spec:
  kind: network
  selector:
    matchLabels:
      nephio.org/address-family: ipv4
      nephio.org/cluster-name: sdcore
  networkInstance:
    name: vpc-internal
status: {prefix: 172.1.1.1/16, gateway: ""}
