apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: sdcore5g/sdcore5g-operator
  namespace: sdcore5g
  name: sdcore5g-operator
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|sdcore5g|sdcore5g-operator'
