apiVersion: v1
kind: Service
metadata: # kpt-merge: /ausf
  name: ausf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: sdcore5g
    nf: ausf
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|ausf'
  namespace: sdcore5g-cp
spec:
  type: ClusterIP
  selector:
    project: sdcore5g
    nf: ausf
  ports:
  - name: sbi
    port: 29509
    protocol: TCP
